# Generated by Django 5.1.2 on 2024-10-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_patientsmodel_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('profile', models.FileField(upload_to='static\\doctorprofiles')),
            ],
            options={
                'db_table': 'DoctorsModel',
            },
        ),
        migrations.AlterField(
            model_name='patientsmodel',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
