# Generated by Django 5.1.2 on 2024-10-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static\\chat_images'),
        ),
    ]
