# Generated by Django 5.1.2 on 2024-10-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_appointmentsmodel_delete_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsmodel',
            name='disease',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointmentsmodel',
            name='symptoms',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appointmentsmodel',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
