# Generated by Django 5.1.2 on 2024-10-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_appointmentsmodel_disease_appointmentsmodel_symptoms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsmodel',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appointmentsmodel',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
