# Generated by Django 5.1.2 on 2024-10-24 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_appointmentsmodel_age_appointmentsmodel_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='static\\reports')),
                ('privatekey', models.TextField()),
                ('publickey', models.TextField()),
                ('status', models.CharField(default='Uploaded', max_length=100)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appointmentsmodel')),
            ],
            options={
                'db_table': 'ReportsModel',
            },
        ),
    ]
