# Generated by Django 5.1.2 on 2024-10-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_reportsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsmodel',
            name='privatekey',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appointmentsmodel',
            name='publickey',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appointmentsmodel',
            name='report',
            field=models.FileField(null=True, upload_to='static\\reports'),
        ),
        migrations.DeleteModel(
            name='ReportsModel',
        ),
    ]
