# Generated by Django 5.1.2 on 2024-10-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_appointmentsmodel_privatekey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsmodel',
            name='key',
            field=models.IntegerField(null=True),
        ),
    ]
