# Generated by Django 5.1.2 on 2024-10-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_feedbackmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('note', models.TextField()),
            ],
            options={
                'db_table': 'FreeQuoteModel',
            },
        ),
    ]
