# Generated by Django 5.1.3 on 2024-12-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_freequote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'specialists',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('specialists', models.ManyToManyField(related_name='diseases_handled', to='app.specialist')),
            ],
            options={
                'db_table': 'diseases',
            },
        ),
    ]
