# Generated by Django 5.1.3 on 2025-02-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_specialist_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsmodel',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
