# Generated by Django 5.1.3 on 2025-02-13 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_doctorsmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('cardnumber', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('expirydate', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='Payment Successfull', max_length=100)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appointmentsmodel')),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
    ]
